#ifndef GAME_LONGHU_SCORE_ANDROID_GLOBAL_H
#define GAME_LONGHU_SCORE_ANDROID_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(GAME_LONGHU_SCORE_ANDROID_LIBRARY)
#  define GAME_LONGHU_SCORE_ANDROIDSHARED_EXPORT
#else
#  define GAME_LONGHU_SCORE_ANDROIDSHARED_EXPORT
#endif

#endif // GAME_LONGHU_SCORE_ANDROID_GLOBAL_H
