#ifndef GAME_BJL_SCORE_ANDROID_GLOBAL_H
#define GAME_BJL_SCORE_ANDROID_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(GAME_BJL_SCORE_ANDROID_LIBRARY)
#  define GAME_BJL_SCORE_ANDROIDSHARED_EXPORT
#else
#  define GAME_BJL_SCORE_ANDROIDSHARED_EXPORT
#endif

#endif // GAME_BJL_SCORE_ANDROID_GLOBAL_H
